# GoFlow golangci-lint configuration
# Minimal configuration to allow commits while project is in active development
version: 2

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - tests
    - pkg/tui/examples
    - specs

linters:
  disable-all: true
  enable:
    - govet

linters-settings: {}

issues:
  exclude-use-default: true
  max-same-issues: 0
